version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    #- contextcheck
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    #- gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    #- gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
