name: main
on:
  push:
    branches:
    - main
jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: make test
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out
