name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write

jobs:

  make-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make lint

  make-test-cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v4
    - uses: actions/checkout@v3
    - run: go mod download
    - run: make test
    - run: go install github.com/mattn/goveralls@v0.0.12
    - run: goveralls -coverprofile=cover.out -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - run: make docker-build
